name = "Vid"
type = "javascript"
account_id = "61295149b323855ef32524950be5c587"
workers_dev = true
compatibility_date = "2024-12-22"
main = "worker.js" # এন্ট্রি-পয়েন্ট উল্লেখ করুন

[vars]
BOT_TOKEN = "7841284508:AAE91Awolci1qRo-8EFz5GyceHuTQWozj40"

[env.production]
route = "https://tarabox-botss.woodmirror.workers.dev/*"
zone_id = "aaf799bb82f97a7acb67e2a97bb16993"
